export const tableData = [
  {
    id: '001',
    title: 'Design System Cleanup',
    author: 'Alice Kim',
    status: 'Published',
    createdAt: '2025-04-10T10:00:00Z',
    updatedAt: '2025-05-19T09:42:00Z',
    isFeatured: true,
    wordCount: 980,
    tags: ['UI', 'Refactor'],
    visibility: 'Public',
    reviewedBy: ['Sam', 'Dana'],
    notes: 'Reviewed and approved for Q2 rollout',
  },
  {
    id: '002',
    title: 'Next.js Route Optimization',
    author: 'Bob Li',
    status: 'Draft',
    createdAt: '2025-04-22T15:20:00Z',
    updatedAt: '2025-05-17T13:12:00Z',
    isFeatured: false,
    wordCount: 1250,
    tags: ['React', 'Next.js'],
    visibility: 'Private',
    reviewedBy: [],
    notes: 'Still awaiting results from load testing',
  },
  {
    id: '003',
    title: 'Accessibility Review Checklist',
    author: 'Carla Mendez',
    status: 'Published',
    createdAt: '2025-03-30T09:10:00Z',
    updatedAt: '2025-04-01T14:45:00Z',
    isFeatured: false,
    wordCount: 560,
    tags: ['Accessibility', 'WCAG', 'Checklist', 'Review', 'UI', 'UX'],
    visibility: 'Public',
    reviewedBy: ['Alice'],
    notes:
      'Needs continuous updates per WCAG updates and follow through with feedback Needs continuous updates per WCAG updates and follow through with feedback ',
  },
  // {
  //   id: '004',
  //   title: 'Refactor Table Logic',
  //   author: 'David Tran',
  //   status: 'Archived',
  //   createdAt: '2025-01-10T08:00:00Z',
  //   updatedAt: '2025-03-15T16:00:00Z',
  //   isFeatured: false,
  //   wordCount: 1870,
  //   tags: ['Tables', 'Logic', 'Performance'],
  //   visibility: 'Private',
  //   reviewedBy: ['Maya', 'Bob'],
  //   notes: 'Deprecated approach; saved for reference',
  // },
  // {
  //   id: '005',
  //   title: 'Client Feedback Tracker',
  //   author: 'Emily Zhao',
  //   status: 'Draft',
  //   createdAt: '2025-05-01T12:05:00Z',
  //   updatedAt: '2025-05-20T11:30:00Z',
  //   isFeatured: true,
  //   wordCount: 300,
  //   tags: ['Clients', 'Feedback'],
  //   visibility: 'Private',
  //   reviewedBy: [],
  //   notes: 'Add latest survey results from enterprise accounts',
  // },
  // {
  //   id: '006',
  //   title: 'AI Content Analysis',
  //   author: 'Frank Rivera',
  //   status: 'Published',
  //   createdAt: '2025-02-15T11:15:00Z',
  //   updatedAt: '2025-05-10T14:00:00Z',
  //   isFeatured: true,
  //   wordCount: 2100,
  //   tags: ['AI', 'Analysis', 'NLP'],
  //   visibility: 'Public',
  //   reviewedBy: ['Alice', 'Carla'],
  //   notes: 'Pending review by legal for dataset usage',
  // },
  // {
  //   id: '007',
  //   title: 'Tailwind vs SCSS Comparison',
  //   author: 'Grace Thomas',
  //   status: 'Published',
  //   createdAt: '2025-03-05T09:30:00Z',
  //   updatedAt: '2025-04-28T13:10:00Z',
  //   isFeatured: false,
  //   wordCount: 1490,
  //   tags: ['CSS', 'Tailwind', 'SCSS'],
  //   visibility: 'Public',
  //   reviewedBy: ['David'],
  //   notes: 'Generated strong engagement on dev blog',
  // },
  // {
  //   id: '008',
  //   title: 'UI Testing Strategy',
  //   author: 'Hector Morales',
  //   status: 'Draft',
  //   createdAt: '2025-04-18T10:30:00Z',
  //   updatedAt: '2025-04-20T09:45:00Z',
  //   isFeatured: false,
  //   wordCount: 890,
  //   tags: ['Testing', 'UI', 'Vitest'],
  //   visibility: 'Private',
  //   reviewedBy: [],
  //   notes: 'Waiting on test coverage data',
  // },
  // {
  //   id: '009',
  //   title: 'Database Schema Migration Guide',
  //   author: 'Isla Nguyen',
  //   status: 'Published',
  //   createdAt: '2025-01-25T12:50:00Z',
  //   updatedAt: '2025-04-05T10:00:00Z',
  //   isFeatured: true,
  //   wordCount: 1720,
  //   tags: ['Database', 'PostgreSQL'],
  //   visibility: 'Public',
  //   reviewedBy: ['Frank', 'Carla'],
  //   notes: 'Used by backend team during 2025 Q1 migration',
  // },
  // {
  //   id: '010',
  //   title: 'Internal Tools Audit',
  //   author: 'Jason Lee',
  //   status: 'Archived',
  //   createdAt: '2024-12-12T08:45:00Z',
  //   updatedAt: '2025-01-02T17:30:00Z',
  //   isFeatured: false,
  //   wordCount: 730,
  //   tags: ['Audit', 'Internal'],
  //   visibility: 'Private',
  //   reviewedBy: ['Emily'],
  //   notes: 'Archived; succeeded by new monitoring dashboard',
  // },
];
