import type { Data } from '../components/types/table';

export const tableData: Data[] = [
  {
    id: '001',
    title: 'Understanding React Server Components',
    url: 'https://vercel.com/blog/react-server-components',
    author: 'Guillermo Rauch',
    status: 'Draft',
    createdAt: '2025-07-01T21:40:01Z',
    updatedAt: '2024-12-14T19:31:16Z',
    isFeatured: false,
    wordCount: 1179,
    tags: ['React', 'Next.js', 'RSC'],
    visibility: 'Private',
    reviewedBy: ['Emily', 'Sam', 'Theo'],
    notes: 'Awaiting final security audit results',
  },
  {
    id: '002',
    title: 'Mitigating SSR Bottlenecks in Edge Environments',
    url: 'https://cloudflare.com/blog/edge-ssr-bottlenecks',
    author: 'Katie Sylor-Miller',
    status: 'Published',
    createdAt: '2024-11-25T02:02:33Z',
    updatedAt: '2024-04-11T00:05:14Z',
    isFeatured: true,
    wordCount: 2227,
    tags: ['Edge', 'SSR'],
    visibility: 'Private',
    reviewedBy: ['Emily', 'Theo'],
    notes: 'Archived for historical reference',
  },
  {
    id: '003',
    title: 'Building Resilient UIs with Remix and React Router',
    url: 'https://remix.run/blog/remix-resilience',
    author: 'Ryan Florence',
    status: 'Published',
    createdAt: '2024-08-18T20:50:15Z',
    updatedAt: '2024-04-09T10:07:29Z',
    isFeatured: false,
    wordCount: 1290,
    tags: ['Remix', 'Routing'],
    visibility: 'Private',
    reviewedBy: ['Alice'],
    notes: 'Still under review by engineering leadership',
  },
  {
    id: '004',
    title: 'Adopting TypeScript at Scale',
    url: 'https://shopify.engineering/typescript-at-scale',
    author: 'Dan Vanderkam',
    status: 'Archived',
    createdAt: '2024-06-07T01:59:59Z',
    updatedAt: '2024-03-10T02:08:58Z',
    isFeatured: true,
    wordCount: 1699,
    tags: ['TypeScript', 'Scaling'],
    visibility: 'Private',
    reviewedBy: ['Theo', 'Maya'],
    notes: 'Considered outdated but useful context',
  },
  {
    id: '005',
    title: "Behind the Scenes: Shopify's Hydrogen Architecture",
    url: 'https://shopify.engineering/hydrogen-architecture',
    author: 'Luna Gao',
    status: 'Archived',
    createdAt: '2025-09-10T09:37:42Z',
    updatedAt: '2025-01-07T18:48:53Z',
    isFeatured: true,
    wordCount: 850,
    tags: ['Shopify', 'Hydrogen'],
    visibility: 'Public',
    reviewedBy: ['David', 'Maya'],
    notes: 'Still under review by engineering leadership',
  },
  {
    id: '006',
    title: 'How Cloudflare Uses Workers to Handle 15B Requests/Day',
    url: 'https://cloudflare.com/blog/cloudflare-workers-architecture',
    author: 'Zack Bloom',
    status: 'Published',
    createdAt: '2025-06-28T07:55:39Z',
    updatedAt: '2025-03-21T00:36:36Z',
    isFeatured: false,
    wordCount: 1894,
    tags: ['Cloudflare', 'Workers', 'Scale'],
    visibility: 'Private',
    reviewedBy: [],
    notes: 'Cross-posted to partner blog',
  },
  {
    id: '007',
    title: 'Using AI to Catch Performance Regressions',
    url: 'https://developer.chrome.com/blog/performance-ai-regressions',
    author: 'Addy Osmani',
    status: 'Draft',
    createdAt: '2024-10-01T06:01:37Z',
    updatedAt: '2024-12-14T15:32:53Z',
    isFeatured: true,
    wordCount: 2399,
    tags: ['AI', 'Performance'],
    visibility: 'Private',
    reviewedBy: ['Lee', 'Sam'],
    notes: 'Used during 2025 Q2 internal workshops',
  },
  {
    id: '008',
    title: 'A Deep Dive into Vite’s Build Process',
    url: 'https://vitejs.dev/guide/build-optimization',
    author: 'Evan You',
    status: 'Published',
    createdAt: '2024-09-01T20:29:08Z',
    updatedAt: '2024-07-23T05:12:51Z',
    isFeatured: false,
    wordCount: 940,
    tags: ['Vite', 'Build', 'Rollup'],
    visibility: 'Public',
    reviewedBy: ['Bob'],
    notes: 'Ready for external publishing',
  },
  {
    id: '009',
    title: 'Design Tokens: A Practical Implementation Guide',
    url: 'https://designsystems.com/articles/design-tokens-guide',
    author: 'Jina Anne',
    status: 'Draft',
    createdAt: '2025-06-06T10:16:49Z',
    updatedAt: '2024-09-27T18:57:44Z',
    isFeatured: true,
    wordCount: 1423,
    tags: ['Design Systems', 'Tokens'],
    visibility: 'Public',
    reviewedBy: ['Maya'],
    notes: 'Pending tech writing edits',
  },
  {
    id: '010',
    title: 'ByteByteGo Guide to Distributed Systems',
    url: 'https://bytebytego.com/distributed-systems-guide',
    author: 'Alex Xu',
    status: 'Archived',
    createdAt: '2025-01-24T00:24:23Z',
    updatedAt: '2024-10-08T13:58:33Z',
    isFeatured: false,
    wordCount: 2134,
    tags: ['Distributed', 'Microservices'],
    visibility: 'Public',
    reviewedBy: ['Theo', 'Emily'],
    notes: 'Shared internally for discussion',
  },
  {
    id: '011',
    title: 'Rust in Production at Dropbox',
    url: 'https://dropbox.tech/infrastructure/rust-in-production',
    author: 'Jon Gjengset',
    status: 'Published',
    createdAt: '2024-11-12T09:10:00Z',
    updatedAt: '2025-02-02T12:20:00Z',
    isFeatured: true,
    wordCount: 1780,
    tags: ['Rust', 'Systems', 'Infrastructure'],
    visibility: 'Public',
    reviewedBy: [],
    notes: 'Core reference for systems migration discussion',
  },
  {
    id: '012',
    title: 'Tailwind CSS v4: Design System Migration',
    url: 'https://tailwindcss.com/blog/tailwindcss-v4',
    author: 'Adam Wathan',
    status: 'Draft',
    createdAt: '2025-03-05T08:45:00Z',
    updatedAt: '2025-05-18T11:12:00Z',
    isFeatured: false,
    wordCount: 1540,
    tags: ['CSS', 'Tailwind', 'Design Systems'],
    visibility: 'Private',
    reviewedBy: ['Alice'],
    notes: 'Large token rename; needs migration codemods',
  },
  {
    id: '013',
    title: 'Prisma Accelerate: Fast Queries at Scale',
    url: 'https://www.prisma.io/blog/prisma-accelerate',
    author: 'Nikolas Burk',
    status: 'Published',
    createdAt: '2025-02-11T14:22:00Z',
    updatedAt: '2025-04-09T09:05:00Z',
    isFeatured: true,
    wordCount: 1320,
    tags: ['Prisma', 'Database', 'Performance'],
    visibility: 'Public',
    reviewedBy: ['Carla', 'Bob'],
    notes: 'Adopted for OSI project query optimization',
  },
  {
    id: '014',
    title: 'Kafka Without ZooKeeper (KRaft) in Production',
    url: 'https://www.confluent.io/blog/kafka-without-zookeeper',
    author: 'Jun Rao',
    status: 'Published',
    createdAt: '2024-12-09T17:40:00Z',
    updatedAt: '2025-01-20T08:12:00Z',
    isFeatured: false,
    wordCount: 2010,
    tags: ['Kafka', 'KRaft', 'Streaming'],
    visibility: 'Public',
    reviewedBy: ['Maya'],
    notes: 'Used by platform team for broker upgrade planning',
  },
  {
    id: '015',
    title: 'Bun 1.0 Performance Profile',
    url: 'https://bun.sh/blog/bun-v1.0',
    author: 'Jarred Sumner',
    status: 'Draft',
    createdAt: '2025-05-12T11:11:00Z',
    updatedAt: '2025-06-21T16:30:00Z',
    isFeatured: false,
    wordCount: 990,
    tags: ['Bun', 'JavaScript', 'Performance'],
    visibility: 'Private',
    reviewedBy: [],
    notes: 'Benchmarks to be replicated on CI runners',
  },
  {
    id: '016',
    title: 'Svelte 5 and the Runes Mental Model',
    url: 'https://svelte.dev/blog/svelte-5-runes',
    author: 'Rich Harris',
    status: 'Published',
    createdAt: '2024-10-22T07:05:00Z',
    updatedAt: '2025-02-03T10:15:00Z',
    isFeatured: false,
    wordCount: 1755,
    tags: ['Svelte', 'Runes', 'Reactivity'],
    visibility: 'Public',
    reviewedBy: ['Lee'],
    notes: 'Team considering rewrite of internal tool spike',
  },
  {
    id: '017',
    title: 'Remix SPA Mode: When You Don’t Need the Server',
    url: 'https://remix.run/blog/spa-mode',
    author: 'Michael Jackson',
    status: 'Published',
    createdAt: '2024-09-14T06:33:00Z',
    updatedAt: '2025-01-12T14:51:00Z',
    isFeatured: true,
    wordCount: 1120,
    tags: ['Remix', 'SPA', 'Routing'],
    visibility: 'Public',
    reviewedBy: ['Ryan'],
    notes: 'Great comparison section vs. Next.js App Router',
  },
  {
    id: '018',
    title: 'Durable Execution Patterns with Temporal',
    url: 'https://temporal.io/blog/durable-execution-patterns',
    author: 'Dominik Tornow',
    status: 'Draft',
    createdAt: '2025-06-03T13:02:00Z',
    updatedAt: '2025-06-28T21:09:00Z',
    isFeatured: false,
    wordCount: 2480,
    tags: ['Temporal', 'Workflows', 'Reliability'],
    visibility: 'Private',
    reviewedBy: ['Carla', 'Emily'],
    notes: 'Proposal to replace home-grown job runner',
  },
  {
    id: '019',
    title: 'tRPC at Scale: End-to-End Type Safety',
    url: 'https://trpc.io/blog/trpc-at-scale',
    author: 'KATT',
    status: 'Published',
    createdAt: '2024-11-03T12:00:00Z',
    updatedAt: '2025-03-15T08:44:00Z',
    isFeatured: true,
    wordCount: 1680,
    tags: ['tRPC', 'Type Safety', 'Full-stack'],
    visibility: 'Public',
    reviewedBy: [],
    notes: 'Evaluated for new greenfield micro-frontend project',
  },
  {
    id: '020',
    title: 'Astro Islands Architecture Deep Dive',
    url: 'https://astro.build/blog/islands-architecture',
    author: 'Fred K. Schott',
    status: 'Archived',
    createdAt: '2024-07-19T09:25:00Z',
    updatedAt: '2024-12-01T22:41:00Z',
    isFeatured: false,
    wordCount: 1325,
    tags: ['Astro', 'Islands', 'Architecture'],
    visibility: 'Public',
    reviewedBy: ['Sam'],
    notes: 'Archived; replaced by partial hydration RFC notes',
  },
];
